package types

import (
	"encoding/json"
	"errors"
	"time"
)

// TaskCreationExecutionVersionV1 isolates the durable creation saga from every
// historical pending action. Migration 028 deliberately defaults rows to v0;
// callers must opt a create_schedule action into this protocol explicitly.
const TaskCreationExecutionVersionV1 int16 = 1

// TaskCreationExecutionVersionV2 is the durable creation protocol for native
// V3 research tasks. V1 remains frozen for Temporal/history replay; callers
// must choose V2 explicitly and must never reinterpret a V1 operation.
const TaskCreationExecutionVersionV2 int16 = 2

// Task-creation terminal/lease errors are deliberately separate from the broad AppError
// codes. Callers must be able to distinguish "another worker owns this", "the
// operation is permanently over", and "my fencing token is stale" without
// parsing a message. Scope mismatches still use ErrNotFound and immutable-CAS
// mismatches use ErrConflict.
var (
	ErrTaskCreationBusy      = errors.New("vane: task creation busy")
	ErrTaskCreationTerminal  = errors.New("vane: task creation terminal")
	ErrTaskCreationLeaseLost = errors.New("vane: task creation lease lost")
	ErrTaskCreationLimit     = errors.New("vane: task creation limit reached")
)

const (
	TaskOperationStatusExecuting TaskOperationStatus = "executing"
	TaskOperationStatusBlocked   TaskOperationStatus = "blocked"
	TaskOperationStatusFailed    TaskOperationStatus = "failed"
)

// TaskCreationPhase is the monotonic checkpoint within a v1 create_schedule
// operation. A phase may only move forward; exact-byte checkpoint replay at the
// current/later phase is idempotent, while different bytes are a conflict.
type TaskCreationPhase string

const (
	TaskCreationPhaseClaimed             TaskCreationPhase = "claimed"
	TaskCreationPhaseCommandSealed       TaskCreationPhase = "command_sealed"
	TaskCreationPhaseTranslationStarted  TaskCreationPhase = "translation_started"
	TaskCreationPhaseDefinitionCompiled  TaskCreationPhase = "definition_compiled"
	TaskCreationPhaseSchedulePrepared    TaskCreationPhase = "schedule_prepared"
	TaskCreationPhaseScheduleEnsured     TaskCreationPhase = "schedule_ensured"
	TaskCreationPhaseDefinitionCommitted TaskCreationPhase = "definition_committed"
	TaskCreationPhaseActivationStarted   TaskCreationPhase = "activation_started"
	TaskCreationPhaseActivated           TaskCreationPhase = "activated"
	TaskCreationPhaseCleanupPending      TaskCreationPhase = "cleanup_pending"
	TaskCreationPhaseCompleted           TaskCreationPhase = "completed"
	TaskCreationPhaseCancelled           TaskCreationPhase = "cancelled"
	TaskCreationPhaseExpired             TaskCreationPhase = "expired"
	TaskCreationPhaseBlocked             TaskCreationPhase = "blocked"
	TaskCreationPhaseFailed              TaskCreationPhase = "failed"
)

// TaskCreationLease is the complete fencing identity required by every mutable
// operation after AcquireTaskCreationOperation. Tenant and user are part of the
// write predicate, not a post-write authorization check.
type TaskCreationLease struct {
	ID         string
	TenantID   int64
	UserID     int64
	LeaseOwner string
	Fence      int64
}

// AcquireTaskCreationOperationParams controls first acquisition and stale
// takeover. LeaseOwner is generated by the caller before the SQL call, so a
// lost response can be replayed with the same owner and recover the same fence.
// The external-effect takeover grace is deliberately not caller-controlled;
// Store persists a fixed safe boundary with every lease.
type AcquireTaskCreationOperationParams struct {
	ID            string
	TenantID      int64
	UserID        int64
	LeaseOwner    string
	LeaseDuration time.Duration
	// ReceiptProvider/ReceiptTarget are required for a pristine operation. Both
	// may be empty only while recovering an already-executing pre-A6 row; that
	// row converges to an audit-only target_unbound receipt unless a later user
	// click atomically binds the original provider resource during takeover.
	ReceiptProvider string
	ReceiptTarget   string
}

// CreateTaskCreationOperationParams is the explicit tenant/user boundary for
// creating a v1 create_schedule operation. Status, tool name, execution
// version, and all saga fields are Store-owned and cannot be supplied by a
// caller. Args must be a strict JSON object (duplicate keys are rejected).
type CreateTaskCreationOperationParams struct {
	ID        string
	TenantID  int64
	UserID    int64
	SessionID *int64
	Args      json.RawMessage
	Summary   string
	ExpiresAt time.Time
}

// CreateResearchTaskCreationOperationV3Params is deliberately a distinct
// type from the retained V1 request. Args is the canonical, server-policy-
// injected V3 approved definition; model-facing task creation never controls
// the execution version or any lease/checkpoint field.
type CreateResearchTaskCreationOperationV3Params struct {
	ID        string
	TenantID  int64
	UserID    int64
	SessionID *int64
	Args      json.RawMessage
	Summary   string
	ExpiresAt time.Time
}

// CommitPausedResearchTaskDefinitionV3ForCreationParams is the exact fenced
// evidence required after the deterministic Temporal schedule has been
// ensured paused. DefinitionPayload is decoded as ApprovedDefinitionV3 by the
// Store; there is intentionally no ToolCalls, Source, subscription, or fetch
// target field in this protocol.
type CommitPausedResearchTaskDefinitionV3ForCreationParams struct {
	Lease                     TaskCreationLease
	TaskID                    string
	DefinitionPayload         []byte
	DefinitionDigest          string
	PreparedSchedule          []byte
	EnsureReceipt             []byte
	TargetAction              []byte
	TargetActionDigest        string
	ActionAuthorizationDigest string
}

// ResearchTaskCreationActivationBindingV3 carries the immutable evidence
// identity across the database/Temporal phase boundary.  Activation may not
// authorize or publish an aggregate merely because its task ID and status
// happen to match: all three digests must still be the ones committed by the
// same fenced creation operation.
type ResearchTaskCreationActivationBindingV3 struct {
	TaskID                    string
	DefinitionDigest          string
	TargetActionDigest        string
	ActionAuthorizationDigest string
}

// CommitPausedCompiledTaskDefinitionForCreationParams binds the A2 aggregate
// write to every immutable proof produced by the same fenced operation. The
// Store does not interpret PreparedSchedule or EnsureReceipt; byte identity is
// the authorization boundary.
type CommitPausedCompiledTaskDefinitionForCreationParams struct {
	Lease            TaskCreationLease
	Definition       PausedCompiledTaskDefinition
	CompiledDigest   string
	PreparedSchedule []byte
	EnsureReceipt    []byte
}

// TaskCreationOperation is the durable v1 view of one create_schedule pending
// action. Exact definition/remote-work checkpoints are []byte because
// PostgreSQL BYTEA preserves their identity; Result is JSON because only its
// semantics are consumed after the operation has become a permanent tombstone.
type TaskCreationOperation struct {
	ID         string
	TenantID   int64
	UserID     int64
	SessionID  *int64
	ToolName   string
	Args       json.RawMessage
	Summary    string
	Status     TaskOperationStatus
	ExpiresAt  time.Time
	ExecutedAt *time.Time
	CreatedAt  time.Time

	ExecutionVersion   int16
	Phase              TaskCreationPhase
	LeaseOwner         string
	LeaseUntil         *time.Time
	TakeoverNotBefore  *time.Time
	Fence              int64
	Attempt            int
	NormalizedCommand  []byte
	CompiledDefinition []byte
	CompiledDigest     string
	PreparedSchedule   []byte
	EnsureReceipt      []byte
	TaskID             string
	Result             json.RawMessage
	ErrorCode          string
	ErrorMessage       string
	ReceiptProvider    string
	ReceiptTarget      string
	UpdatedAt          time.Time
	TombstonedAt       *time.Time
}

// Lease returns the fencing identity represented by the loaded/acquired row.
func (o TaskCreationOperation) Lease() TaskCreationLease {
	return TaskCreationLease{
		ID:         o.ID,
		TenantID:   o.TenantID,
		UserID:     o.UserID,
		LeaseOwner: o.LeaseOwner,
		Fence:      o.Fence,
	}
}
