package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/YouToco/vane/tikhubcatalog"
)

type staticTool struct {
	name, capability, params, risk, exposure, confirmation, production string
}

var staticTools = []staticTool{
	{"list_sources", "列出信源", "无", "内部只读", "信源意图首轮", "无", "启用"},
	{"add_source", "试跑并添加信源", "平台、能力及目标参数", "外部读取+owner 写入", "明确订阅意图首轮", "目标唯一时直办", "启用"},
	{"remove_source", "退订信源", "信源 ID 列表", "owner 写入", "明确退订意图首轮", "目标唯一时直办", "启用"},
	{"enable_source", "恢复信源", "信源 ID 列表", "owner 写入", "明确恢复意图首轮", "目标唯一时直办", "启用"},
	{"list_schedules", "列出任务", "无", "内部只读", "任务意图首轮", "无", "启用"},
	{"create_schedule", "生成任务创建方案", "频率、意图、已批准抓取计划", "耐久提案", "任务意图首轮", "一张确认卡", "启用"},
	{"remove_schedule", "删除任务", "任务 ID 列表", "owner 写入", "明确删除意图首轮", "目标唯一时直办", "启用"},
	{"push_now", "立即执行/推送", "任务 ID", "外部投递", "明确立即运行意图首轮", "直办", "启用"},
	{"view_profile", "查看画像", "无", "内部只读", "画像意图首轮", "无", "启用"},
	{"update_profile", "生成画像更新", "画像字段", "owner 写入", "画像意图首轮", "一张确认卡", "启用"},
	{"view_task_playbook", "查看任务手册", "任务 ID", "内部只读", "任务意图首轮", "无", "启用"},
	{"edit_task_definition", "生成任务整体编辑方案", "任务 ID 与目标定义", "耐久提案", "任务意图首轮", "一张确认卡", "条件启用"},
	{"web_search", "搜索公开网页", "query、结果数、域名", "外部只读/可能计费", "网页研究首轮", "无", "条件启用"},
	{"read_page", "读取公开页面", "url", "外部只读/可能计费", "网页研究首轮", "无", "条件启用"},
	{"search_endpoints", "搜索社媒查询工具", "query、platform", "本地目录激活", "社媒研究首轮", "无", "条件启用"},
	{"read_endpoint_result", "续读本轮结果句柄", "handle、path、offset、limit", "外部结果本地续读", "产生句柄后", "无", "条件启用"},
}

func main() {
	output := flag.String("out", "docs/agent-tool-inventory.md", "inventory output")
	check := flag.Bool("check", false, "fail if the committed inventory differs")
	flag.Parse()

	content := render()
	if *check {
		existing, err := os.ReadFile(*output)
		if err != nil || !bytes.Equal(existing, content) {
			fmt.Fprintln(os.Stderr, "agent tool inventory is stale; run: go run ./cmd/agenttoolinventory")
			os.Exit(1)
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*output, content, 0o644); err != nil {
		panic(err)
	}
}

func render() []byte {
	var b strings.Builder
	b.WriteString("# Agent Tool Inventory\n\n")
	b.WriteString("Generated by `go run ./cmd/agenttoolinventory`; CI rejects drift. Provider routing, HTTP paths and internal versions are intentionally excluded from this model-facing inventory.\n\n")
	b.WriteString("## Static production tools\n\n")
	b.WriteString("| Tool | Capability | Parameters | Risk | Exposure | Confirmation | Production |\n")
	b.WriteString("|---|---|---|---|---|---|---|\n")
	for _, tool := range staticTools {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n",
			tool.name, tool.capability, tool.params, tool.risk,
			tool.exposure, tool.confirmation, tool.production)
	}
	b.WriteString("\nRemoved legacy contracts: `update_schedule`, `edit_task_playbook`, `set_task_strictness`.\n\n")
	b.WriteString("## Dynamic social research tools\n\n")
	fmt.Fprintf(&b, "%d read-only catalog tools are discovered lazily through `search_endpoints`; schemas are not placed in the first model request.\n\n", tikhubcatalog.AgentLen())
	b.WriteString("| Tool | Platform | Capability | Parameters | Risk | Exposure | Confirmation | Production |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|\n")
	entries := tikhubcatalog.Entries()
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
	for _, entry := range entries {
		params := make([]string, 0, len(entry.Params))
		for _, param := range entry.Params {
			name := param.Name
			if param.Required {
				name += "*"
			}
			params = append(params, name)
		}
		exposure := "搜索命中后"
		if advanced(entry) {
			exposure = "明确广告/店铺/创作者分析意图且搜索命中后"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | 公开数据只读/可能计费 | %s | 无 | 目录启用 |\n",
			entry.Name, entry.Platform, capability(entry),
			escape(strings.Join(params, ", ")), exposure)
	}
	return []byte(b.String())
}

func capability(entry tikhubcatalog.Entry) string {
	text := strings.ToLower(entry.Name + " " + entry.Summary)
	for _, item := range []struct{ marker, label string }{
		{"comment", "评论"}, {"search", "搜索"}, {"hot", "热榜/趋势"},
		{"trend", "趋势"}, {"user", "账号"}, {"detail", "内容详情"},
		{"list", "内容列表"}, {"analytics", "公开分析"},
	} {
		if strings.Contains(text, item.marker) {
			return item.label
		}
	}
	return "公开数据查询"
}

func advanced(entry tikhubcatalog.Entry) bool {
	text := strings.ToLower(entry.Name + " " + entry.Tag + " " + entry.Summary)
	for _, marker := range []string{"douplus", "xingtu", "广告", "投放", "shop", "commerce", "merchant", "创作者分析", "达人分析"} {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}

func escape(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
